git:
  depth: false

matrix:
  include:

    - os: linux
      name: node.js Package
      #if: (branch !~ ^r/.*$ AND head_branch !~ ^r/.*$) AND ((type = push AND branch = master) OR type = pull_request OR tag =~ /^v\d+\.\d+\.\d+$/)

      dist: bionic
      language: generic

      script:
        - cd tools/nodejs
        - ./configure
        - npm install
#        - cibuildwheel --output-dir wheelhouse duckdb_tarball
#        - cd ../..
#        - |
#          if [[ $TRAVIS_TAG ]] || ([ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]) ; then
#            python -m twine upload --non-interactive --disable-progress-bar --skip-existing tools/pythonpkg/wheelhouse/*.whl
#          fi

    - os: osx
      name: node.js Package
      #if: (branch !~ ^r/.*$ AND head_branch !~ ^r/.*$) AND ((type = push AND branch = master) OR type = pull_request OR tag =~ /^v\d+\.\d+\.\d+$/)

      language: generic
      osx_image: xcode11.5

      script:
        - cd tools/nodejs
        - ./configure
        - npm install
#        - cibuildwheel --output-dir wheelhouse duckdb_tarball
#        - cd ../..
#        - |
#          if [[ $TRAVIS_TAG ]] || ([ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]) ; then
#            twine upload --non-interactive --disable-progress-bar --skip-existing tools/pythonpkg/wheelhouse/*.whl
#          fi
