name: "Setup Ubuntu 16"
description: "Setup an Ubuntu 16 docker container with the required libraries"
inputs:
  openssl:
    description: 'OpenSSL'
    default: 0
  arch32bit:
    description: '32-Bit Architecture'
    default: 0
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        yum install -y gcc gcc-c++ git cmake make
        yum install -y epel-release
        yum install -y git make gcc perl-core pcre-devel wget zlib-devel python3

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Version Check
      shell: bash
      run: |
        ldd --version ldd
        python3 --version
        git --version
        git log -1 --format=%h

    - name: Install i686 dependencies
      shell: bash
      if: ${{ inputs.arch32bit }} == 1
      run: |
        yum install -y glibc-devel.i686 libgcc.i686 libstdc++-devel.i686 ncurses-devel.i686
#
#      # the weird openssl findreplace fix with version numbers is from: https://github.com/h2o/h2o/issues/213
#    - name: Download OpenSSL 1.1.1k
#      run: |
#        wget https://ftp.openssl.org/source/openssl-1.1.1k.tar.gz --no-check-certificate
#        tar -xzvf openssl-1.1.1k.tar.gz
#        cd openssl-1.1.1k
#        find ./ -type f -exec sed -i -e 's/\#\ define\ OPENSSL\_VERSION\_NUMBER/\#define\ OPENSSL\_VERSION\_NUMBER/g' {} \;
#
#    - name: Configure OpenSSL x86_64
#      if: ${{matrix.arch == 'x86_64'}}
#      run: |
#        cd openssl-1.1.1k
#        ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
#
#    - name: Configure OpenSSL i686
#      if: ${{matrix.arch == 'i686'}}
#      run: |
#        cd openssl-1.1.1k
#        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic -m32 linux-generic32
#
#    - name: Build OpenSSL
#      run: |
#        cd openssl-1.1.1k
#        make
#        make install
#
#
#
#
