name: "Setup CentOS7"
description: "Setup the CentOS7 container from manylinux"
inputs:
  aws-cli:
    description: 'Install aws-cli'
    default: 0
  ninja-build:
    description: 'Install ninja-build'
    default: 0
  vcpkg:
    description: 'Install vcpkg'
    default: 0
  openssl:
    description: 'Install OpenSSL (requires vcpkg)'
    default: 0
  ccache:
    description: 'Setup Ccache'
    default: 0
  jdk:
    description: 'Setup JDK'
    default: 0

runs:
  using: "composite"
  steps:
#    - name: Install dependencies
#      shell: bash
#      run: |
#        yum install -y gcc gcc-c++ cmake make
#        yum install -y epel-release
#        yum install -y make gcc perl-core pcre-devel wget zlib-devel python3
#        yum install -y https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
#        yum install -y git
#        yum install -y curl-devel expat-devel gettext-devel zlib-devel perl-ExtUtils-MakeMaker ninja-build
#        yum install -y unixODBC-devel
#        yum install -y java-11-openjdk-devel maven

    - name: Do the git permissions thing
      shell: bash
      run: |
        git config --global --add safe.directory '*'

    - name: Install AWS CLI
      if: ${{ inputs.aws-cli == 1 }}
      shell: bash
      run: |
        python3 -m pip install awscli
        aws --version

    - name: Setup dependencies for building DuckDB
      if: ${{ inputs.ninja-build == 1 }}
      shell: bash
      run: yum install -y ninja-build

    - name: Setup dependencies for vcpkg
      if: ${{ inputs.vcpkg == 1 }}
      shell: bash
      run: yum install -y curl zip unzip tar

    - name: Setup dependencies for installing OpenSSL through vcpkg
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: yum install -y perl-IPC-Cmd

    - name: Setup vcpkg
      if: ${{ inputs.vcpkg == 1 }}
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1

    - name: Install OpenSSL
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: |
        cd ${{ github.workspace }}/vcpkg
        ./vcpkg install openssl

    - name: Setup Ccache
      if: ${{ inputs.ccache == 1 }}
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}

    - name: Setup JDK
      if: ${{ inputs.jdk == 1 }}
      shell: bash
      run: yum install -y java-11-openjdk-devel maven