name: "Setup manylinux2014 image"
description: "Installs/configures additional CI dependencies"
inputs:
  aws-cli:
    description: 'Setup aws-cli'
    default: 0
  ninja-build:
    description: 'Setup ninja-build'
    default: 0
  vcpkg:
    description: 'Setup vcpkg (installs to $GITHUB_WORKSPACE/vcpkg)'
    default: 0
  openssl:
    description: 'Setup OpenSSL (requires vcpkg to also be installed)'
    default: 0
  ccache:
    description: 'Setup Ccache'
    default: 0
  jdk:
    description: 'Setup JDK'
    default: 0
  odbc:
    description: 'Setup ODBC'
    default: 0
  ssh:
    description: 'Setup SSH'
    default: 0
  glibc32:
    description: 'Setup 32bit glibc'
    default: 0
  gcc_4_8:
    description: 'Setup GCC 4.8 (installs to /usr/bin/g++, default will still be GCC 10)'
    default: 0

runs:
  using: "composite"
  steps:
    - name: Do the git permissions thing
      shell: bash
      run: |
        git config --global --add safe.directory '*'

    - name: Setup general dependencies
      shell: bash
      run: yum install -y curl zip unzip tar

    - name: Install AWS CLI
      if: ${{ inputs.aws-cli == 1 }}
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        aws --version

    - name: Setup dependencies for building DuckDB quickly
      if: ${{ inputs.ninja-build == 1 }}
      shell: bash
      run: yum install -y ninja-build

    - name: Setup dependencies for ODBC
      if: ${{ inputs.odbc == 1 }}
      shell: bash
      run: yum install -y unixODBC-devel

    - name: Setup dependencies for installing OpenSSL through vcpkg
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: yum install -y perl-IPC-Cmd

    - name: Setup dependencies for ccache
      if: ${{ inputs.ccache == 1 }}
      shell: bash
      run: yum -y install ccache

    - name: Setup vcpkg
      if: ${{ inputs.vcpkg == 1 }}
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 501db0f17ef6df184fcdbfbe0f87cde2313b6ab1

    - name: Install OpenSSL
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/vcpkg
        ./vcpkg install openssl

    - name: Setup Ccache
      if: ${{ inputs.ccache == 1 }}
      uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ github.job }}
        save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}

    - name: Setup JDK
      if: ${{ inputs.jdk == 1 }}
      shell: bash
      run: yum install -y java-11-openjdk-devel maven

    - name: Setup SSH
      if: ${{ inputs.ssh == 1 }}
      shell: bash
      run: yum install -y openssh-clients

    - name: Setup 32bit compiler
      if: ${{ inputs.glibc32 == 1 }}
      shell: bash
      run: yum install -y libgcc*i686 libstdc++*i686 glibc*i686 libgfortran*i686

    - name: Setup old (GCC 4.8) compiler
      if: ${{ inputs.gcc_4_8 == 1 }}
      shell: bash
      run: yum install -y gcc-c++