# Marks all changed PR as draft
name: Draft on Synchronize
on:
  pull_request:
    types: [ synchronize ]

env:
  TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  mark-as-draft:
    name: Mark as draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        shell: bash
        run: |
          echo ${{ env.TOKEN }} | gh auth login --with-token
          gh api graphql -F id=${{ github.event.pull_request.node_id }} -f query='
            mutation($id: ID!) {
              convertPullRequestToDraft(input: { pullRequestId: $id }) {
                pullRequest {
                  id
                  number
                  isDraft
                }
              }
            }
          '
