name: Julia
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Julia ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.7'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Build DuckDB
        run: |
            make

      - name: Set Julia DuckDB Library Path
        run: |
          export JULIA_DUCKDB_LIBRARY="`pwd`/build/release/src/libduckdb.so"
          ls $JULIA_DUCKDB_LIBRARY

      - name: Run Tests
        run: |
          cd tools/juliapkg
          ./test.sh

