on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
  codecov:
    name: CodeCov
    runs-on: ubuntu-20.04
    env:
      GEN: ninja
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build lcov

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Before Install
        run: |
          pip install --prefer-binary "pandas>=1.2.4" "requests>=2.26" "pyarrow>=5.0" pytest
          sudo apt-get install g++

      - name: Coverage Reset
        run: |
          lcov --config-file .github/workflows/lcovrc --zerocounters --directory .
          lcov --config-file .github/workflows/lcovrc --capture --initial --directory . --base-directory . --no-external --output-file coverage.info

      - name: Run Tests
        run: |
          mkdir -p build/coverage
          (cd build/coverage && cmake -E env CXXFLAGS="--coverage" cmake -DBUILD_PYTHON=1 -DBUILD_PARQUET_EXTENSION=1 -DENABLE_SANITIZER=0 -DCMAKE_BUILD_TYPE=Debug ../.. && make)
          (cd tools/pythonpkg/tests && python3 -m pytest)
          build/coverage/test/unittest
          build/coverage/test/unittest "[intraquery]"
          build/coverage/test/unittest "[interquery]"
          python3 scripts/try_timeout.py --timeout=1200 --retry=3 build/coverage/test/unittest "[coverage]"
          build/coverage/test/unittest "[detailed_profiler]"
          build/coverage/test/unittest "[tpch]"
          build/coverage/tools/sqlite3_api_wrapper/test_sqlite3_api_wrapper
          python tools/shell/shell-test.py build/coverage/duckdb


      - name: Generate Coverage
        run: |
          lcov --config-file .github/workflows/lcovrc --directory . --base-directory . --no-external --capture --output-file coverage.info
          lcov --config-file .github/workflows/lcovrc --remove coverage.info $(< .github/workflows/lcov_exclude) -o lcov.info

      - name: CodeCov Upload
        uses: codecov/codecov-action@v1
        with:
          files: lcov.info
          fail_ci_if_error: true
