on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
  coverage:
    name: Coveralls
    runs-on: ubuntu-20.04
#    needs: linux-debug
# COVERALLS_REPO_TOKEN


    env:
      GEN: ninja
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install
      run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build lcov

    - name: Coverage Reset
      run: |
        lcov --zerocounters --directory .
        lcov --capture --initial --directory . --base-directory . --no-external --output-file coverage.info

    - name: Build
      run: |
        mkdir -p build/coverage
        (cd build/coverage && cmake -E env CXXFLAGS="--coverage" cmake -DCMAKE_BUILD_TYPE=Debug ../.. && make)
        build/coverage/test/unittest

    - name: Generate Coverage
      run: |
        lcov --directory . --base-directory . --no-external --capture --output-file coverage.info
        lcov --remove coverage.info '/usr*' '*/cl.hpp' 'tools/*' 'benchmark/*' 'examples/*' 'third_party/*' 'test/*' -o lcov.info

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        path-to-lcov: ./lcov.info
