name: PythonDebug
on:
  [push, pull_request]
jobs:
 python-debug-linux:
    name: Linux (64 Bit)
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    env:
      GEN: ninja
      BUILD_BENCHMARK: 1
      BUILD_ICU: 1
      BUILD_TPCH: 1
      BUILD_FTS: 1
      BUILD_REST: 1
      BUILD_JDBC: 1
      BUILD_JSON: 1
      BUILD_EXCEL: 1
      TREAT_WARNINGS_AS_ERRORS: 1
      FORCE_WARN_UNUSED: 1

    steps:
    - name: Install
      run: |
        apt-get update -y -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update -y -qq
        apt-get install -y -qq git ninja-build make gcc-multilib g++-multilib libssl-dev wget openjdk-8-jdk zip maven unixodbc-dev

    - name: Install Python 3.7
      run: |
        wget https://www.python.org/ftp/python/3.7.12/Python-3.7.12.tgz
        tar xvf Python-3.7.12.tgz
        cd Python-3.7.12
        mkdir -p pythonbin
        ./configure --with-ensurepip=install --with-pydebug  
        make -j
        make install
        python3.7 --version
        python3.7 -m pip install pip
        python3.7 -m pip install requests
        python3.7 -m pip install cibuildwheel
        pwd
        cd ..

    - name: Build
      run: |
        cd tools/pythonpkg
        python3.7 setup.py sdist
        mkdir duckdb_tarball && tar xvf dist/duckdb-*.tar.gz --strip-components=1 -C duckdb_tarball
        cibuildwheel --output-dir wheelhouse --config-file cibw.toml duckdb_tarball