name: PythonDebug
on:
  [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
 python-debug-mac:
    name: Python Address Sanitizer (Mac Os)
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    env:
      GEN: ninja
      BUILD_PYTHON: 1
      TREAT_WARNINGS_AS_ERRORS: 1
      FORCE_WARN_UNUSED: 1
      DUCKDEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install
      run: |
        apt-get update -y -qq
        apt-get install -y -qq software-properties-common
        add-apt-repository ppa:git-core/ppa
        apt-get update -y -qq
        apt-get install -y -qq git ninja-build make gcc-multilib g++-multilib libssl-dev wget openjdk-8-jdk zip maven unixodbc-dev libffi-dev


    - name: Install Python 3.9
      run: |
        wget https://github.com/python/cpython/archive/refs/tags/v3.9.12.zip
        unzip v3.9.12.zip
        rm v3.9.12.zip
        cd cpython-3.9.12
        mkdir debug-build
        ./configure --with-ensurepip=install --with-address-sanitizer --with-undefined-behavior-sanitizer --prefix=${GITHUB_WORKSPACE}/debug-build --with-openssl=/opt/homebrew/opt/openssl@3/
        make -j
        make install
        export PATH=${GITHUB_WORKSPACE}/debug-build/bin/:$PATH
        python3 -m pip install numpy
        python3 -m pip install pandas
        python3 -m pip install arrow
        python3 -m pip install pytest
        python3 -m pip install psutil

    - name: Install CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-linux-x86_64.sh
        chmod +x cmake-3.21.3-linux-x86_64.sh
        ./cmake-3.21.3-linux-x86_64.sh --skip-license --prefix=/usr/local

    - name: Build
      run: |
        cd tools/pythonpkg
        python3 setup.py install

    - name: Run Tests
      run: python3 -m pytest {project}/tests/fast
