name: PythonDebug
on:
  [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/master' || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
 python-debug-mac:
    name: Python Address Sanitizer (Linux)
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    env:
      GEN: ninja
      DUCKDEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/ubuntu_16_setup
      with:
        openssl: 0
        python: 0

    - name: Run Python with sanitizer on
      run: |
        export DUCKDEBUG=1
        export ASAN_OPTIONS=detect_leaks=0
        apt-get install -y -qq libbz2-dev
        
        wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
        tar -xf openssl-1.0.2o.tar.gz
        cd openssl-1.0.2o
        ./config shared --prefix=/usr/local/
        make
        make install
        mkdir lib
        cp ./*.{so,so.1.0.0,a,pc} ./lib
        
        cd ..
        
        wget https://github.com/python/cpython/archive/refs/tags/v3.9.12.zip
        unzip v3.9.12.zip
        rm v3.9.12.zip
        cd cpython-3.9.12
        mkdir debug-build
        export LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/openssl-1.0.2o/lib
        ./configure --with-ensurepip=install --with-address-sanitizer --with-undefined-behavior-sanitizer --with-openssl=${GITHUB_WORKSPACE}/openssl-1.0.2o --prefix=${GITHUB_WORKSPACE}/debug-build
        make -j
        make install
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pip install numpy
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pip install pandas
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pip install pyarrow
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pip install pytest
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pip install psutil
        cd ../tools/pythonpkg
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 setup.py install
        ${GITHUB_WORKSPACE}/debug-build/bin/python3 -m pytest tests/fast
