on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
  win-nodejs:
    name: node.js Windows
    runs-on: windows-latest
    # needs: linux-debug

    strategy:
      matrix:
        # node: [ '10', '12', '14', '15' ]
        node: [ '14' ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Node
      run: ./scripts/node_build_win.sh
