on: [push, pull_request]

defaults:
  run:
    shell: bash

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
  AWS_ACCESS_KEY_ID: AKIAVBLKPL2ZW2T7TYFQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

jobs:
  win-nodejs:
    name: node.js Windows
    runs-on: windows-latest
    # needs: linux-debug

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup
      run: ./scripts/node_version.sh

    - name: Node 10
      run: ./scripts/node_build.sh 10

    - name: Node 12
      run: ./scripts/node_build.sh 12

    - name: Node 14
      run: ./scripts/node_build.sh 14

    - name: Node 15
      run: ./scripts/node_build.sh 15
